### ISSUE TITLE
Uncaught Error: Can't save destroyed buffer

### ISSUE THREAD

**Issue by paidTrainee27** [nju33/atom-pane-browser#14]
Error: Can't save destroyed buffer
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\ibspl_java1\AppData\Local\atom\app-1.17.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:1114:1)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\ibspl_java1\AppData\Local\atom\app-1.17.1\resources\app\node_modules\text-buffer\lib\text-buffer.js:1108:1)
    at TextEditor.module.exports.TextEditor.save (C:\Users\ibspl_java1\AppData\Local\atom\app-1.17.1\resources\app\src\text-editor.js:925:1)
    at file:///C:/Users/ibspl_java1/.atom/packages/pane-browser/lib/pane.coffee:109:18
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\ibspl_java1\AppData\Local\atom\app-1.17.1\resources\app\node_modules\event-kit\lib\emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (C:\Users\ibspl_java1\AppData\Local\atom\app-1.17.1\resources\app\node_modules\event-kit\lib\emitter.js:141:1)
    at Pane.module.exports.Pane.destroy (C:\Users\ibspl_java1\AppData\Local\atom\app-1.17.1\resources\app\src\pane.js:885:1)
    at Pane.module.exports.Pane.close (C:\Users\ibspl_java1\AppData\Local\atom\app-1.17.1\resources\app\src\pane.js:1055:1)
    at atom-pane.pane:close (C:\Users\ibspl_java1\AppData\Local\atom\app-1.17.1\resources\app\src\register-default-commands.js:304:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\ibspl_java1\AppData\Local\atom\app-1.17.1\resources\app\src\command-registry.js:265:1)
    at CommandRegistry.handleCommandEvent (C:\Users\ibspl_java1\AppData\Local\atom\app-1.17.1\resources\app\src\command-registry.js:3:1)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\ibspl_java1\AppData\Local\atom\app-1.17.1\resources\app\src\command-registry.js:166:1)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\ibspl_java1\AppData\Local\atom\app-1.17.1\resources\app\src\atom-environment.js:1300:1)
    at EventEmitter.outerCallback (C:\Users\ibspl_java1\AppData\Local\atom\app-1.17.1\resources\app\src\application-delegate.js:334:1)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

**Comment by paidTrainee27** [comment]
I got This error while I was trying to close the browser..(pane browser)
